/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feluletek;

import vezerlo.Vezerlo;

/**
 *
 * @author varga
 */
public class MenuPanel extends javax.swing.JPanel {

    private Vezerlo vezerlo;
    private int pont, ido;

    public void setPont(int pont) {
        this.pont = pont;
    }

    public void setIdo(int ido) {
        this.ido = ido;
    }

    /**
     * Creates new form MenuPanel
     */
    public MenuPanel() {
        initComponents();
        lbl_Pont.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Sugo = new javax.swing.JButton();
        btn_Eredmenyek = new javax.swing.JButton();
        btn_Belepes = new javax.swing.JButton();
        btn_Start = new javax.swing.JButton();
        lbl_Pont = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 204, 255));
        setMaximumSize(new java.awt.Dimension(800, 100));
        setMinimumSize(new java.awt.Dimension(800, 100));
        setPreferredSize(new java.awt.Dimension(800, 100));

        btn_Sugo.setBackground(new java.awt.Color(255, 255, 255));
        btn_Sugo.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18)); // NOI18N
        btn_Sugo.setForeground(new java.awt.Color(201, 149, 45));
        btn_Sugo.setText("Súgó");
        btn_Sugo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SugoActionPerformed(evt);
            }
        });

        btn_Eredmenyek.setBackground(new java.awt.Color(255, 255, 255));
        btn_Eredmenyek.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18)); // NOI18N
        btn_Eredmenyek.setForeground(new java.awt.Color(201, 149, 45));
        btn_Eredmenyek.setText("Eredmények");
        btn_Eredmenyek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EredmenyekActionPerformed(evt);
            }
        });

        btn_Belepes.setBackground(new java.awt.Color(255, 255, 255));
        btn_Belepes.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18)); // NOI18N
        btn_Belepes.setForeground(new java.awt.Color(201, 149, 45));
        btn_Belepes.setText("Belépés");
        btn_Belepes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BelepesActionPerformed(evt);
            }
        });

        btn_Start.setBackground(new java.awt.Color(255, 255, 255));
        btn_Start.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18)); // NOI18N
        btn_Start.setForeground(new java.awt.Color(201, 149, 45));
        btn_Start.setText("Játék indítása");
        btn_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_StartActionPerformed(evt);
            }
        });

        lbl_Pont.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Belepes)
                .addGap(18, 18, 18)
                .addComponent(lbl_Pont, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Start)
                .addGap(98, 98, 98)
                .addComponent(btn_Eredmenyek)
                .addGap(18, 18, 18)
                .addComponent(btn_Sugo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Sugo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Eredmenyek, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Belepes, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Start, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lbl_Pont, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SugoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SugoActionPerformed
        vezerlo.sugoClick();
    }//GEN-LAST:event_btn_SugoActionPerformed


    private void btn_EredmenyekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EredmenyekActionPerformed
        vezerlo.eredmenyClick();
    }//GEN-LAST:event_btn_EredmenyekActionPerformed

    private void btn_BelepesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BelepesActionPerformed
        vezerlo.belepesClick();
    }//GEN-LAST:event_btn_BelepesActionPerformed

    private void btn_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_StartActionPerformed
        vezerlo.startClick();
    }//GEN-LAST:event_btn_StartActionPerformed

    public void setVezerlo(Vezerlo vezerlo) {
        this.vezerlo = vezerlo;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Belepes;
    private javax.swing.JButton btn_Eredmenyek;
    private javax.swing.JButton btn_Start;
    private javax.swing.JButton btn_Sugo;
    private javax.swing.JLabel lbl_Pont;
    // End of variables declaration//GEN-END:variables

    public void gombAllapot(boolean b) {
        btn_Eredmenyek.setEnabled(b);
        btn_Start.setEnabled(b);
        btn_Belepes.setEnabled(!b);
    
    }

    public void lblFrissit() {

        lbl_Pont.setText(pont + " pont\t" + ido + " mp");
    }

    public void gombAktivitas(String eredmeny, boolean b) {
        switch(eredmeny){
            case "start":
                btn_Start.setEnabled(b);
                break;
            case "eredmeny":
                btn_Eredmenyek.setEnabled(b);
                break;
        }
    }
}
