/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feluletek;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.KeyEvent;
import vezerlo.Vezerlo;

/**
 *
 * @author varga
 */
public class RajzPanel extends javax.swing.JPanel {

    private Vezerlo vezerlo;
    private Image hatterKep;

    public void setHatterKep(Image hatterKep) {
        this.hatterKep = hatterKep;
    }

    /**
     * Creates new form RajzPanel
     */
    public RajzPanel() {
        initComponents();
    }

    public void setVezerlo(Vezerlo vezerlo) {
        this.vezerlo = vezerlo;
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.drawImage(hatterKep, 0, 0, this);
        vezerlo.rajzolas(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 0, 0));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
/**
 * Megnézi melyik gombot nyomtuk le és továbbküldi a vezérlőnek
 * @param evt 
 */
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        int key = evt.getKeyCode();
        switch (key) {
            case KeyEvent.VK_SPACE:
                vezerlo.gomblenyom(0);
                break;
            case KeyEvent.VK_LEFT:
                vezerlo.gomblenyom(-1);
                break;
            case KeyEvent.VK_RIGHT:
                vezerlo.gomblenyom(1);
                break;
        }
        

    }//GEN-LAST:event_formKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
